### ISSUE TITLE
 Class "Symfony\Component\HttpFoundation\Response" not found  

### ISSUE THREAD

**Issue by iYting** [mouyong/php-support#1]
大佬 这个报错不应该啊 我都是按照文档上的步骤操作的
Error: Class "Symfony\Component\HttpFoundation\Response" not found in /vagrant/php7433/webman/vendor/zhenmu/support/src/Traits/WebmanResponseTrait.php:152
Stack trace:
#0 /vagrant/php7433/webman/app/controller/indexController.php(12): app\controller\WebmanBaseController->success()
#1 /vagrant/php7433/webman/vendor/workerman/webman-framework/src/App.php(319): app\controller\IndexController->index()
#2 /vagrant/php7433/webman/vendor/workerman/webman-framework/src/App.php(168): Webman\App::Webman\{closure}()
#3 /vagrant/php7433/webman/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage()
#4 [internal function]: Workerman\Connection\TcpConnection->baseRead()
#5 /vagrant/php7433/webman/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#6 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(1635): Workerman\Events\Event->loop()
#7 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#8 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#9 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(1785): Workerman\Worker::forkWorkers()
#10 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(1721): Workerman\Worker::monitorWorkersForLinux()
#11 /vagrant/php7433/webman/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#12 /vagrant/php7433/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#13 /vagrant/php7433/webman/start.php(4): support\App::run()
#14 {main} [] []

**Comment by www295686243** [comment]
我用webman也是出现这个错误，不知道为啥

**Comment by mouyong** [comment]
最近没测试了。可能是依赖的代码被改过了

**Comment by mouyong** [comment]
https://github.com/mouyong/php-support/blob/master/src/Traits/WebmanResponseTrait.php#L152 主要用在了这里。

之前我记得 webman 支持的。估计 webman 改了依赖吧！

**Comment by mouyong** [comment]
@www295686243 @iYting 方便测试看看webman的response改了什么吗。这个调整感觉不麻烦。我最近没用webman。

**Comment by www295686243** [comment]
> @www295686243 @iYting 方便测试看看webman的response改了什么吗。这个调整感觉不麻烦。我最近没用webman。

之前不清楚，反正目前webman它不会默认安装symfony/http-foundation，所以导致引用错误，自己安装下就这样用了
